name: gh-actions-test event

on:
  workflow_run:
    workflows: ["gh-actions-test Single Releases"]
    branches: [master]
    types:
      - completed

jobs:
  uploadToBuildBot:
    name: Upload to buildboot
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ toJson(github) }}"
          echo "${{ toJson(job) }}"
          echo "${{ toJson(steps) }}"
          echo "${{ toJson(runner) }}"
          echo "${{ toJson(strategy) }}"
          echo "${{ toJson(matrix) }}"