name: gh-actions-test Single Releases

on:
  push:
    branches:
      - master

jobs:
  buildAndTag:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - run: zip -9 my-release.zip my-file.txt
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: myrelease
        prerelease: false
        title: My Release 2
        files: |
          my-release.zip
    - uses: actions/upload-artifact@v2
      with:
        name: my-release
        path: my-release.zip

  uploadFile:
    name: Upload
    runs-on: ubuntu-latest

    steps:
    - name: Get core from artifacts
      uses: actions/download-artifact@v2
      with:
        name: my-release
        path: .
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: .