name: gh-actions-test Releases

on:
  push:
    branches:
      - master

jobs:
  buildAndTag:
    name: Build and Tag
    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - run: zip -9 my-release.zip my-file.txt
    - name: Create or Replace Release
      id: create_release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: myrelease
        name: My Release
        name:  My Release
        gzip: false
        allow_override: yes
        files: >
          my-release.zip